// Generated by hand from the real running backend's OpenAPI schema
// (GET /openapi.json against G1's agent/g1-api, merged into main). Keep in
// sync with backend/app/contracts if the schema changes.

export type ChatStatus =
  | 'answered'
  | 'needs_clarification'
  | 'insufficient_evidence'
  | 'temporarily_unavailable'

export type DataMode = 'synthetic'

export interface ChatHistoryMessage {
  role: 'user' | 'assistant'
  content: string
}

export interface ProcedureSelection {
  document_id: string
  version: string
  section_id: string
}

export interface ChatSelection {
  assembly_id?: string
  part_id?: string
  procedure?: ProcedureSelection
}

export interface ChatRequest {
  message: string
  history?: ChatHistoryMessage[]
  selection?: ChatSelection
}

export interface Citation {
  citation_id: string
  document_id: string
  version: string
  section_id: string
  title: string
  quoted_text: string
  source_uri: string
}

export interface SourceIdentity {
  document_id: string
  version: string
  section_id: string
  is_current: boolean
}

export interface ProcedureStep {
  step_id: string
  text: string
  ordinal: number
  citation_ids: string[]
  explanation?: string | null
}

export interface WarningBlock {
  warning_id: string
  text: string
  applies_to_step_ids: string[]
  citation_ids: string[]
}

export interface Prerequisite {
  id: string
  text: string
  citation_ids: string[]
}

export interface ProcedureResult {
  state: 'ok' | 'no_evidence' | 'conflict' | 'unavailable'
  sources: SourceIdentity[]
  steps: ProcedureStep[]
  warnings: WarningBlock[]
  prerequisites: Prerequisite[]
  explanation?: string | null
  fallback_used: boolean
}

export interface Snapshot {
  snapshot_id: string
  captured_at: string
}

export type InventoryState = 'ok' | 'ambiguous' | 'not_found' | 'incomplete' | 'unavailable'

export interface BuildComponent {
  part_id: string
  per_assembly: number
  required: number
  available: number | null
  shortage: number | null
}

export interface BuildInventoryResult {
  kind: 'build'
  state: InventoryState
  snapshot: Snapshot | null
  assembly_id: string
  requested_units: number
  ready: boolean | null
  components: BuildComponent[]
}

export interface StockMatch {
  part_id: string
  label: string
  available: number | null
  unit: string
}

export interface StockInventoryResult {
  kind: 'stock'
  state: InventoryState
  snapshot: Snapshot | null
  matches: StockMatch[]
}

export type InventoryResult = BuildInventoryResult | StockInventoryResult

export type ClarificationKind = 'assembly' | 'part' | 'quantity' | 'procedure'

export interface ClarificationChoice {
  id: string
  label: string
}

export interface Clarification {
  kind: ClarificationKind
  question: string
  choices?: ClarificationChoice[]
}

export interface ApiError {
  code: string
  message: string
  retryable: boolean
}

export interface ChatResponse {
  answer: string
  answer_citation_ids: string[]
  status: ChatStatus
  citations: Citation[]
  procedure_result: ProcedureResult | null
  inventory_result: InventoryResult | null
  clarification: Clarification | null
  error: ApiError | null
  trace_id: string
  data_mode: DataMode
}

/** Envelope returned for a 422 validation failure — distinct from ChatResponse. */
export interface ValidationErrorResponse {
  error: ApiError
  trace_id: string
  data_mode: DataMode
}

export interface SopSection {
  document_id: string
  version: string
  section_id: string
  title: string
  text: string
  source_uri: string
  is_current: boolean
}

export interface Assembly {
  assembly_id: string
  label: string
}

export interface ReadyResponse {
  status: 'ready' | 'not_ready'
  database: 'ready' | 'unavailable'
  corpus: 'ready' | 'missing' | 'unavailable'
  provider: 'configured' | 'missing'
}
